<footer class="footer">
  <p>&copy; 2014 December Wedding</p>
  <p>All rights reserved</p>
  <ul class="social-media">
    <li><a class="icon icon--qq" href="#"></a></li>
    <li>
      <a class="icon icon--wechat" data-lightbox-dec href="/wechat"></a>
      <div class="lightbox-dec lightbox--wechat">
        <a class="lightbox__close" href="#">&times;</a>
        <h1 class="lightbox__title">Follow Us</h1>
        <div class="lightbox__intro">
          <p>扫描二维码，关注「拾贰记」微信公众号，获取最新资讯</p>
        </div>
        <img class="lightbox__img" src="/sites/all/themes/december/images/wechat_qr.png"/>
      </div>
    </li>
    <li><a class="icon icon--weibo" href="http://weibo.com/decemberwedding12"></a></li>
  </ul>
  <div class="footer__to-top">
    <a class="icon icon--up-arrow" href="#"></a>
  </div>
</footer>