<footer class="footer">
  <p>&copy; 2014 December Wedding</p>
  <p>All rights reserved</p>
  <ul class="social-media">
    <li><a class="icon icon--qq" data-lightbox-dec="" href="#">&nbsp;</a>

      <div class="lightbox-dec lightbox--wechat"><a class="lightbox__close"
                                                    href="#">&nbsp;</a>

        <h1 class="lightbox__title">Contact Us</h1>

        <div class="lightbox__intro">
          <p>请给我们的QQ客服留言，我们会尽快答复您的疑问</p>

          <p>QQ: 2096788836 / 2985867077</p>
        </div>
      </div>
    </li>
    <li><a class="icon icon--wechat" data-lightbox-dec="" href="/wechat">
        &nbsp;</a>

      <div class="lightbox-dec lightbox--wechat"><a class="lightbox__close"
                                                    href="#">&nbsp;</a>
        <h1 class="lightbox__title">Follow Us</h1>
        <div class="lightbox__intro">
          <p>扫描二维码，关注「拾贰记」微信公众号，获取最新资讯</p>
        </div>
        <img class="lightbox__img"
             src="/sites/all/themes/december/images/wechat_qr.png"/></div>
    </li>
    <li><a class="icon icon--weibo" href="http://weibo.com/decemberwedding12" target="_blank">
        &nbsp;</a></li>
  </ul>

  <div class="footer__to-top"><a class="icon icon--up-arrow" href="#">&nbsp;</a>
  </div>
</footer>
