<div class="control">
  <ul class="control__type">
    <li class="control__type--unit active">
      <a class="link" href="#">婚礼</a>
    </li>
    <li class="control__type--unit">
      <a class="link" href="#">求婚</a>
    </li>
    <li class="control__type--unit">
      <a class="link" href="#">活动</a>
    </li>
    <li class="control__type--unit">
      <a class="link" href="#">视频</a>
    </li>
  </ul>
  <div class="control__switch">
    <a class="control__switch--list link icon icon--list" href="#"></a>
    <a class="control__switch--tile link icon icon--tile" href="#"></a>
  </div>
</div>