<div class="related">
    <h2 class="related__title">类似作品</h2>
    <ul class="related__list row">
        <li class="related__item" style="background-image: url(/sites/all/themes/december/images/product_1.png);"></li>
        <li class="related__item" style="background-image: url(/sites/all/themes/december/images/product_2.png);"></li>
        <li class="related__item" style="background-image: url(/sites/all/themes/december/images/product_3.png);"></li>
    </ul>
</div>