<nav class="site-nav">
  <ul class="site-nav__list">
    <li class="site-nav__item"><a href="/products-list?tid=All">作品展示</a></li>
    <li class="site-nav__item"><a href="#">服务流程</a></li>
    <li class="site-nav__logo">
      <img src="/sites/all/themes/december/images/logo.png">
    </li>
    <li class="site-nav__logo--fix">
      <img src="/sites/all/themes/december/images/logo_small.png">
    </li>
    <li class="site-nav__item"><a href="#">关于我们</a></li>
    <li class="site-nav__item"><a href="#">联系我们</a></li>
  </ul>
</nav>